let package_name = OpamPackage.Name.of_string "opam-doc-base"
let cache_file = "opam-doc-xml-index.cache"
let cache_magic_number = "OpamDocDB001"
let root_name = "xml"
let modules_dir_name = "modules"
let module_types_dir_name = "modules"
let pkg_idx_name = "index.xml"
let lib_idx_name = "index.xml"
